name: Release Workflow

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: blender-octane-library-generator
          exclude-files: ".git;.github;README.md;.gitignore;*auto_load.py;.vscode;images"

  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Release addon
        uses: blenderkit/blender-addon-release@main
        with:
          artifact_name: blender-octane-library-generator
          release_name: BlenderOctaneLibraryGenerator
          version: ${{github.event.inputs.version}}
